spring:
  datasource:
    url: jdbc:mariadb://localhost:33306/reservation
    driver-class-name: org.mariadb.jdbc.Driver
    username: reservation_user
    password: a1234

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDB103Dialect